trigger:
  branches:
    include:
      - master
  tags:
    include:
      - '*'

variables:
  WinGenerator: Visual Studio 16 2019
  WinType: x64
  RuntimeURL: https://atom.io/download/atom-shell
  RuntimeName: iojs
  RuntimeVersion: v6.0.3
  DistributionAritfact: $(RuntimeName)-$(RuntimeVersion)-color-picker

jobs:
- job: 'Windows64'
  pool:
    vmImage: 'windows-2019'

  workspace:
    clean: all

  steps:
  - powershell: git config --global core.autocrlf false
    displayName: 'Set Unix checkout for git'

  - checkout: self
    fetchDepth: 10

  - task: NodeTool@0
    displayName: 'Install Node'
    inputs:
      versionSpec: '10.x'

  - script: 'yarn install'
    displayName: 'Install dependencies'

  - script: './ci/win-build.cmd'
    displayName: 'Build color-picker'

  - task: ArchiveFiles@2
    displayName: 'Generate artifact'
    inputs:
      rootFolderOrFile: build\distribute\color-picker
      includeRootFolder: false
      archiveType: tar
      tarCompression: gz
      archiveFile: '$(DistributionAritfact)-win.tar.gz'

  - task: CopyFiles@2
    displayName: "Copy artifact to staging directory"
    inputs:
      sourceFolder: $(Build.SourcesDirectory)
      contents: '*.tar.gz'
      targetFolder: $(Build.ArtifactStagingDirectory)
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish pipeline artifact'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactName: win64

  - task: S3Upload@1
    inputs:
      awsCredentials: 'Streamlabs AWS'
      regionName: 'us-west-2'
      bucketName: 'obs-studio-deployment'
      globExpressions: '$(DistributionAritfact)-win.tar.gz'
      filesAcl: 'public-read'
    displayName: 'Upload artifact to S3'
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'tags'))
